### PR TITLE
Keep history of bank during migration (on/off)

### PR DESCRIPTION
**Pull request by horkko**
Hi,

I've updated biomaj-migrate.py in order to be able to keep the history of a bank while migrating to biomaj3. This is an option (`-H/--keep_history`) to pass to the script.
The history is simply taken from the MySQL table 'productionDirectory'.
I've tested both cases (with and without `-H`) and it looks to be working as expected.
I've also, with this, added storage of the logfile of the old session (if available in the database and on disk).
Let me know what do you think?

Emmanuel

### CODE REVIEW

**Comment by osallou** [comment]
please ask merge against branch develop

**Comment by horkko** [comment]
Ok but your project biomaj-migrate doesn't have a branch develop :(

On 13 January 2016 at 16:34, Olivier Sallou notifications@github.com
wrote:

> please ask merge against branch develop
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/genouest/biomaj-migrate/pull/3#issuecomment-171332772
> .

## 

Emmanuel Quevillon
email: horkko at gmail _dot com

**Comment by horkko** [comment]
Ok but it looks like yout project biomaj-migrate doesn't have a branch develop

**Comment by osallou** [comment]
My fault... I did not check. I will do the merge, i can t test it but am
confudent with yours

**Comment by horkko** [comment]
Don't forget to create a new release, I've change the release number in `setup.py` to 3.0.2

**Comment by osallou** [comment]
biomaj-migrate si standalone and not on pypi, so no specific release

**Pull request merged**
